@extends('layouts.guest')
@section('content')
<div class="login-split"><div class="login-split-left"><div class="login-card">@if($appSettings->logoUrl())<img class="login-logo" src="{{ $appSettings->logoUrl() }}" alt="{{ $appSettings->displayName() }}">@else<div class="logo">{{ $appSettings->displayName() }}</div>@endif<div class="sub">{{ __('Sign in to continue') }}</div>
@error('google')<div class="error-msg">{{ __($message) }}</div>@enderror @error('email')<div class="error-msg">{{ __($message) }}</div>@enderror
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($googleConfigured)<a class="btn btn-full google-login-btn" href="{{ route('auth.google.redirect') }}"><span class="google-mark" aria-hidden="true">G</span>{{ __('Continue with Google') }}</a>@elseif($googleLoginOnly)<div class="error-msg">{{ __('Google sign-in is enabled but its configuration is incomplete.') }}</div>@endif
@if($googleConfigured && !$googleLoginOnly)<div class="login-dev-sep">{{ __('or') }}</div>@endif
@unless($googleLoginOnly)<form method="POST" action="{{ route('login.store') }}">@csrf<div class="field"><label for="email">{{ __('Email') }}</label><input id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="username" required autofocus></div><div class="field"><label for="password">{{ __('Password') }}</label><input id="password" name="password" type="password" autocomplete="current-password" required></div><button class="btn btn-full" type="submit">{{ __('Sign in') }}</button></form><a class="mt-4 block text-center text-sm text-indigo-600 hover:underline" href="{{ route('password.request') }}">{{ __('Forgot your password?') }}</a>@endunless
@if($isLocal)<div class="login-dev-sep">{{ __('dev shortcuts') }}</div><div class="login-dev-actions"><form method="POST" action="{{ route('dev-login', 'admin') }}">@csrf<button class="btn btn-full login-dev-btn" type="submit">{{ __('Login as Admin') }}</button></form><form method="POST" action="{{ route('dev-login', 'operator') }}">@csrf<button class="btn btn-full login-dev-btn" type="submit">{{ __('Login as User') }}</button></form></div>@endif
</div></div><div class="login-split-right" aria-hidden="true"><img src="{{ $appSettings->loginImageUrl() }}" alt=""></div></div>
@endsection
