@extends('layouts.app')
@section('content')
<nav class="breadcrumb" aria-label="Breadcrumb"><a href="{{ route('dashboard') }}">Shopify Ops</a><span class="breadcrumb-sep">›</span><span class="breadcrumb-current">Dashboard</span></nav>
<div class="topbar"><div><h1>Dashboard</h1><div class="meta">{{ $activeStore->label }} · {{ $activeStore->shopify_store }}.myshopify.com</div></div><div class="flex gap-2">@can('run-audits')<a class="btn btn-sm" href="{{ route('reports.run-audit') }}">Run Audit</a>@endcan @can('manage-administration')<form method="POST" action="{{ route('admin.cache.flush') }}">@csrf<button class="btn btn-sm btn-ghost" type="submit">Flush cache</button></form>@endcan</div></div>
<div class="db-cards"><article class="db-card {{ ($latest?->rows_found ?? 0)>0?'db-card--warn':'db-card--ok' }}"><div class="db-card-label">Latest audit</div><div class="db-card-num">{{ $latest?->rows_found ?? '—' }}</div><div class="db-card-sub">@if($latest)missing · {{ $latest->report_date->toDateString() }}@if($previousMissing!==null) · was {{ $previousMissing }}@endif @else No audits yet @endif</div></article><article class="db-card"><div class="db-card-label">All-time audits</div><div class="db-card-num">{{ $totalReports }}</div><div class="db-card-sub">{{ $totalMissing }} total missing</div></article><article class="db-card"><div class="db-card-label">Pushes</div><div class="db-card-num">{{ $pushesToday }}</div><div class="db-card-sub">today · {{ $pushesMonth }} in 30 days</div></article><article class="db-card {{ $ignoredCount>0?'db-card--warn':'' }}"><div class="db-card-label">Ignored orders</div><div class="db-card-num">{{ $ignoredCount }}</div><div class="db-card-sub"><a href="{{ route('ignored-orders.index') }}">Manage ignored orders</a> · {{ $staleIgnoredCount }} stale (30d+)</div></article><article class="db-card"><div class="db-card-label">Audit cadence</div><div class="db-card-num">{{ $auditCadenceDays ?? '—' }}</div><div class="db-card-sub">avg days between audits</div></article><article class="db-card"><div class="db-card-label">Avg resolution</div><div class="db-card-num">{{ $avgResolutionDays ?? '—' }}</div><div class="db-card-sub">days to clear a missing order</div></article><article class="db-card {{ ($oldestMissingAge ?? 0)>7?'db-card--warn':'' }}"><div class="db-card-label">Oldest missing</div><div class="db-card-num">{{ $oldestMissingAge ?? '—' }}</div><div class="db-card-sub">days since placed</div></article></div>
@if($sevenDayChart->isNotEmpty())<section class="db-section"><div class="db-section-title">Last {{ $sevenDayChart->count() }} audits</div><div class="flex items-end gap-2" style="height:80px">@php($max = max(1, $sevenDayChart->max('missing')))@foreach($sevenDayChart as $point)<div class="flex flex-col items-center gap-1" title="{{ $point['date'] }}: {{ $point['missing'] }} missing"><div style="width:24px;height:{{ max(4, (int) ($point['missing']/$max*70)) }}px;background:#6366f1;border-radius:4px 4px 0 0"></div><span class="text-xs text-slate-500">{{ substr($point['date'], 5) }}</span></div>@endforeach</div></section>@endif
@if($missingByType!==[])<section class="db-section"><div class="db-section-title">Missing by type</div><ul class="db-quick-grid">@foreach($missingByType as $type => $count)<li>{{ $type }}: {{ $count }}</li>@endforeach</ul></section>@endif
<section class="table-wrap db-section"><div class="table-header"><div><h2>Action queue</h2><span>Missing orders from the latest audit.</span></div>@if($latest)<a href="{{ route('saved-reports.show',$latest) }}">Full snapshot</a>@endif</div>@if(!$latest)<div class="no-reports"><div class="icon">📋</div><h2>No audits yet</h2><p>Run the first audit to build the queue.</p></div>@elseif($missingOrders===[])<div class="empty"><div class="icon">✓</div><h3>All clear</h3><p>No missing orders.</p></div>@else<div class="overflow-x-auto"><table><thead><tr><th>Order</th><th>Date</th><th>Email</th><th>Total</th></tr></thead><tbody>@foreach($missingOrders as $order)<tr><td class="order-num">{{ $order['name']??$order['order_number']??'—' }}</td><td>{{ $order['created_at']??'—' }}</td><td>{{ $order['email']??'—' }}</td><td>{{ number_format((float)($order['total_price']??0),2) }}</td></tr>@endforeach</tbody></table></div>@endif</section>
@can('run-audits')<section class="db-section"><div class="db-section-title">Quick actions</div><div class="db-quick-grid">@foreach([['📋','Run Audit','reports.run-audit'],['🏠','Address Check','reports.address-check'],['✉','Email Check','reports.email-check'],['📦','Bundle Check','reports.bundle-check'],['⏳','Partial Stalls','reports.partial-fulfillment'],['🔎','Orphan Orders','reports.orphan-orders']] as [$icon,$label,$name])<a class="db-quick-btn" href="{{ route($name) }}"><span class="icon">{{ $icon }}</span>{{ $label }}</a>@endforeach</div></section>@endcan
@endsection
