<?php
declare(strict_types=1);

require_once __DIR__ . '/Client.php';
require_once __DIR__ . '/Ids.php';
require_once __DIR__ . '/QueryStrings.php';
require_once __DIR__ . '/FieldFragments.php';
require_once __DIR__ . '/Queries.php';
require_once __DIR__ . '/OrderComponentNormalizer.php';
require_once __DIR__ . '/OrderNormalizer.php';
require_once __DIR__ . '/EventNormalizer.php';
require_once __DIR__ . '/MetafieldNormalizer.php';
require_once __DIR__ . '/ProductNormalizer.php';
require_once __DIR__ . '/Normalizer.php';
require_once __DIR__ . '/OrderFetcher.php';
require_once __DIR__ . '/OrderArchive.php';
require_once __DIR__ . '/OrderQueryAudits.php';
require_once __DIR__ . '/OrderEventAudits.php';
require_once __DIR__ . '/OrderAudits.php';
require_once __DIR__ . '/OrderDirectLookup.php';
require_once __DIR__ . '/OrderHoldLookup.php';
require_once __DIR__ . '/OrderEventLookup.php';
require_once __DIR__ . '/OrderLookup.php';
require_once __DIR__ . '/CustomDataLookups.php';
require_once __DIR__ . '/OrderTagInsights.php';
require_once __DIR__ . '/CustomerOrderInsights.php';
require_once __DIR__ . '/DuplicateOrderInsights.php';
require_once __DIR__ . '/OrderInsights.php';
require_once __DIR__ . '/AdminLookups.php';
require_once __DIR__ . '/CatalogAndFulfillment.php';
