@extends('layouts.app')

@section('content')
<div class="flex flex-col gap-6">
<section><p class="text-sm font-medium text-indigo-600 dark:text-indigo-400">Customer report</p><h1 class="mt-1 text-3xl font-bold">Customer LTV & Cohorts</h1><p class="mt-2 text-slate-500 dark:text-slate-400">Top customers by non-cancelled revenue and monthly repeat-buyer cohorts within the selected period.</p></section>
<form class="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-3 dark:border-slate-800 dark:bg-slate-900" method="POST" action="{{ route('reports.customer-ltv.store') }}">@csrf
@foreach (['start_date' => ['From', $startDate], 'end_date' => ['To', $endDate]] as $field => [$label, $value])<div><label class="text-sm font-medium" for="{{ $field }}">{{ $label }}</label><input class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-950" id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field, $value) }}">@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
<div class="flex items-end"><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white" type="submit">Run report</button></div></form>
@if($configurationError)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Shopify credentials are incomplete for the active store.</div>@endif
@if($reportFailed)<div class="rounded-xl bg-red-50 p-4 text-red-800">The report could not be completed. Check Shopify and try again.</div>@endif
@if($result)<section class="flex flex-col gap-4"><h2 class="text-2xl font-bold">{{ $result->scanned }} orders · {{ $result->customers }} customers · ${{ number_format($result->revenue, 2) }}</h2>@if($result->truncated)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Results are incomplete: orders truncated after {{ $result->pages }} pages.</div>@endif
<div class="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><h3 class="p-4 text-lg font-bold">Top customers</h3><table class="min-w-full text-left text-sm"><thead><tr><th class="px-4 py-3">Email</th><th class="px-4 py-3">Orders</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Average</th><th class="px-4 py-3">First / last</th></tr></thead><tbody>@forelse($result->topCustomers as $customer)<tr><td class="px-4 py-3">{{ $customer['email'] }}</td><td class="px-4 py-3">{{ $customer['orders'] }}</td><td class="px-4 py-3">${{ number_format($customer['total'], 2) }}</td><td class="px-4 py-3">${{ number_format($customer['average'], 2) }}</td><td class="px-4 py-3">{{ $customer['first_date'] }} / {{ $customer['last_date'] }}</td></tr>@empty<tr><td class="px-4 py-8 text-center text-slate-500" colspan="5">No customers found.</td></tr>@endforelse</tbody></table></div>
@if($result->cohorts)<div class="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><h3 class="p-4 text-lg font-bold">Monthly cohorts</h3><table class="min-w-full text-left text-sm"><thead><tr><th class="px-4 py-3">Month</th><th class="px-4 py-3">Customers</th><th class="px-4 py-3">Repeat buyers</th><th class="px-4 py-3">Repeat rate</th><th class="px-4 py-3">Avg orders</th><th class="px-4 py-3">Revenue / customer</th></tr></thead><tbody>@foreach($result->cohorts as $cohort)<tr><td class="px-4 py-3">{{ $cohort['month'] }}</td><td class="px-4 py-3">{{ $cohort['customers'] }}</td><td class="px-4 py-3">{{ $cohort['repeat_buyers'] }}</td><td class="px-4 py-3">{{ $cohort['retention_rate'] }}%</td><td class="px-4 py-3">{{ $cohort['average_orders'] }}</td><td class="px-4 py-3">${{ number_format($cohort['average_revenue'], 2) }}</td></tr>@endforeach</tbody></table></div>@endif
</section>@endif
</div>
@endsection
