@extends('layouts.app')

@section('content')
<div class="flex flex-col gap-6">
<section><p class="text-sm font-medium text-indigo-600 dark:text-indigo-400">Risk report</p><h1 class="mt-1 text-3xl font-bold">Duplicate Detector</h1><p class="mt-2 text-slate-500 dark:text-slate-400">Find order pairs with the same customer email and total placed no more than 10 minutes apart.</p></section>
<form class="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-3 dark:border-slate-800 dark:bg-slate-900" method="POST" action="{{ route('reports.duplicate-orders.store') }}">@csrf
@foreach (['start_date' => ['From', $startDate], 'end_date' => ['To', $endDate]] as $field => [$label, $value])<div><label class="text-sm font-medium" for="{{ $field }}">{{ $label }}</label><input class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-950" id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field, $value) }}">@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
<div class="flex items-end"><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white" type="submit">Run report</button></div></form>
@if($configurationError)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Shopify credentials are incomplete for the active store.</div>@endif
@if($reportFailed)<div class="rounded-xl bg-red-50 p-4 text-red-800">The report could not be completed. Check Shopify and try again.</div>@endif
@if($result)<section class="flex flex-col gap-4"><h2 class="text-2xl font-bold">{{ $result->scanned }} scanned · {{ count($result->pairs) }} duplicate pairs</h2>@if($result->truncated)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Results are incomplete: orders truncated after {{ $result->pages }} pages.</div>@endif
<div class="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><table class="min-w-full text-left text-sm"><thead><tr><th class="px-4 py-3">Order A</th><th class="px-4 py-3">Order B</th><th class="px-4 py-3">Email</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Gap</th><th class="px-4 py-3">Statuses</th></tr></thead><tbody>
@forelse($result->pairs as $pair) @php($first = $pair['first']) @php($second = $pair['second'])<tr class="align-top"><td class="px-4 py-3">@if($first['id'])<a class="text-indigo-600" href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $first['id'] }}" target="_blank" rel="noopener noreferrer">{{ $first['name'] }}</a>@else{{ $first['name'] }}@endif<br><span class="text-xs text-slate-500">{{ substr((string) $first['created_at'], 0, 16) }}</span></td><td class="px-4 py-3">@if($second['id'])<a class="text-indigo-600" href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $second['id'] }}" target="_blank" rel="noopener noreferrer">{{ $second['name'] }}</a>@else{{ $second['name'] }}@endif<br><span class="text-xs text-slate-500">{{ substr((string) $second['created_at'], 0, 16) }}</span></td><td class="px-4 py-3">{{ $first['email'] }}</td><td class="px-4 py-3">{{ $first['currency'] ?? '' }} {{ number_format((float) $first['total_price'], 2) }}</td><td class="px-4 py-3">{{ intdiv($pair['gap_seconds'], 60) }}m {{ $pair['gap_seconds'] % 60 }}s</td><td class="px-4 py-3">{{ $first['financial_status'] ?: '-' }} / {{ $second['financial_status'] ?: '-' }}</td></tr>
@empty<tr><td class="px-4 py-8 text-center text-slate-500" colspan="6">No orders shared the same email and total within 10 minutes.</td></tr>@endforelse
</tbody></table></div></section>@endif
</div>
@endsection
