@extends('layouts.app')
@section('content')
<div class="flex flex-col gap-6"><section><p class="text-sm font-medium text-indigo-600">Audit report</p><h1 class="text-3xl font-bold">High-value orders without phone</h1><p class="mt-2 text-slate-500">Paid, unfulfilled orders whose shipping address has no phone number.</p></section>
<form class="grid gap-4 rounded-xl border bg-white p-5 sm:grid-cols-5 dark:border-slate-800 dark:bg-slate-900" method="POST" action="{{ route('reports.high-value-no-phone.store') }}">@csrf
@foreach(['start_date' => ['From', $startDate], 'end_date' => ['To', $endDate]] as $field => [$label, $value])<div><label class="text-sm font-medium" for="{{ $field }}">{{ $label }}</label><input class="mt-2 w-full rounded-lg border px-3 py-2 dark:bg-slate-950" id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field, $value) }}">@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
<div><label class="text-sm font-medium" for="minimum">Minimum value</label><input class="mt-2 w-full rounded-lg border px-3 py-2 dark:bg-slate-950" id="minimum" name="minimum" type="number" min="0" step="0.01" value="{{ old('minimum', $minimum) }}">@error('minimum')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="text-sm font-medium" for="currency">Currency</label><input class="mt-2 w-full rounded-lg border px-3 py-2 uppercase dark:bg-slate-950" id="currency" name="currency" maxlength="3" value="{{ old('currency', $currency) }}">@error('currency')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div class="flex items-end"><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white">Run report</button></div></form>
@if($reportFailed)<div class="rounded-xl border border-red-200 bg-red-50 p-5 text-red-800" role="alert">The report could not be completed. Check the Shopify integration and try again.</div>@endif
@if($result)<section class="flex flex-col gap-4"><div class="flex flex-wrap gap-3"><h2 class="text-2xl font-bold">Results</h2><span>{{ $result->scanned }} scanned · {{ count($result->rows) }} issues</span></div>@if($result->truncated)<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-800">Results were truncated after {{ $result->pages }} pages.</div>@endif
@forelse($result->rows as $row)<article class="rounded-xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div class="flex justify-between gap-4"><div>@if($row['id'])<a class="font-semibold text-indigo-600" href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $row['id'] }}" target="_blank" rel="noopener noreferrer">{{ $row['number'] }}</a>@else<strong>{{ $row['number'] }}</strong>@endif<p class="text-sm text-slate-500">{{ $row['created_at'] }} · {{ $row['email'] ?: 'No email' }}</p><p class="mt-2 text-sm">{{ $row['recipient'] }}@if($row['recipient'] && $row['address']), @endif{{ $row['address'] }}</p></div><strong>{{ number_format($row['total'], 2) }} {{ $row['currency'] }}</strong></div><a class="mt-3 inline-flex text-sm text-indigo-600" href="{{ route('orders.spot-check', ['prefill' => ltrim($row['number'], '#')]) }}">Open in spot-check</a></article>@empty<div class="rounded-xl border bg-white p-5 text-slate-500">No high-value orders without a shipping phone were found.</div>@endforelse</section>@endif</div>
@endsection
