@extends('layouts.app')
@section('content')
<div class="flex flex-col gap-6"><section><p class="text-sm font-medium text-indigo-600">Operations</p><h1 class="text-3xl font-bold">Run audit</h1><p class="text-slate-500">Find active Shopify orders missing from ShipStation.</p></section>
@if(session('status'))<div class="rounded-xl bg-green-50 p-4">{{ session('status') }}</div>@endif @error('queue')<div class="rounded-xl bg-red-50 p-4">{{ $message }}</div>@enderror
<form class="grid gap-4 rounded-xl border p-5 sm:grid-cols-4" method="POST">@csrf @foreach(['start_date'=>['From',$startDate],'end_date'=>['To',$endDate]] as $field=>[$label,$value])<div><label for="{{ $field }}">{{ $label }}</label><input class="w-full rounded-lg border px-3 py-2" id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field,$value) }}">@error($field)<p class="text-red-600">{{ $message }}</p>@enderror</div>@endforeach<button class="rounded-lg bg-indigo-600 px-5 py-2 text-white" formaction="{{ route('reports.run-audit.store') }}">Run now</button><button class="rounded-lg border px-5 py-2" formaction="{{ route('reports.run-audit.queue') }}">Queue</button></form>
@if($configurationError)<div class="rounded-xl bg-amber-50 p-4">Shopify and ShipStation credentials are required for the active store.</div>@endif @if($reportFailed)<div class="rounded-xl bg-red-50 p-4">The audit could not be completed. Check both integrations and try again.</div>@endif
@if($result)<h2 class="text-2xl font-bold">{{ $result->shopifyTotal }} Shopify orders · {{ count($result->missing) }} missing</h2><div class="grid gap-3 sm:grid-cols-4"><div class="rounded-xl border p-4">Found: {{ $result->found }}</div><div class="rounded-xl border p-4">Skipped: {{ $result->skipped }}</div><div class="rounded-xl border p-4">Ignored: {{ $result->ignored }}</div><div class="rounded-xl border p-4">ShipStation: {{ $result->shipstationTotal }}</div></div>@if($result->shopifyTruncated)<div class="rounded-xl bg-amber-50 p-4">Results are incomplete because Shopify data was truncated.</div>@endif
<div class="overflow-x-auto rounded-xl border"><table class="min-w-full text-left"><thead><tr><th class="p-3">Order</th><th>Date</th><th>Email</th><th>Total</th></tr></thead><tbody>@forelse($result->missing as $order)<tr><td class="p-3 font-semibold">{{ $order['name'] ?? $order['order_number'] ?? '—' }}</td><td>{{ $order['created_at'] ?? '—' }}</td><td>{{ $order['email'] ?? '—' }}</td><td>{{ number_format((float) ($order['total_price'] ?? 0), 2) }}</td></tr>@empty<tr><td class="p-6 text-center" colspan="4">Every eligible Shopify order was found in ShipStation.</td></tr>@endforelse</tbody></table></div>@endif</div>
@endsection
