@extends('layouts.app')
@section('content')
<div class="flex flex-col gap-6"><section><h1 class="text-3xl font-bold">Metafields</h1><p class="mt-2 text-slate-500">Browse order metafield definitions, search by value, or inspect up to 20 orders.</p></section>
@if($configurationError)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Shopify credentials are incomplete for the active store.</div>@endif
@if($loadFailed)<div class="rounded-xl bg-red-50 p-4 text-red-800">Metafield definitions could not be loaded.</div>@endif
@if($operationFailed)<div class="rounded-xl bg-red-50 p-4 text-red-800">The metafield operation could not be completed.</div>@endif
<section class="rounded-xl border bg-white p-5 dark:bg-slate-900"><h2 class="text-xl font-bold">Order definitions</h2><div class="mt-3 overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th>Namespace.key</th><th>Name</th><th>Type</th><th>Description</th></tr></thead><tbody>@forelse($definitions as $definition)<tr><td>{{ $definition['namespace'] }}.{{ $definition['key'] }}</td><td>{{ $definition['name'] ?? '' }}</td><td>{{ $definition['type']['name'] ?? '' }}</td><td>{{ $definition['description'] ?? '' }}</td></tr>@empty<tr><td colspan="4">No definitions found.</td></tr>@endforelse</tbody></table></div></section>
<form class="grid gap-3 rounded-xl border bg-white p-5 sm:grid-cols-3 dark:bg-slate-900" method="POST" action="{{ route('metafields.search') }}">@csrf<h2 class="sm:col-span-3 text-xl font-bold">Search orders by metafield</h2>@foreach(['namespace','key','value'] as $field)<input class="rounded border px-3 py-2" name="{{ $field }}" placeholder="{{ ucfirst($field) }}" value="{{ old($field) }}">@error($field)<p class="text-red-600">{{ $message }}</p>@enderror @endforeach<input type="date" name="start_date" value="{{ old('start_date') }}"><input type="date" name="end_date" value="{{ old('end_date') }}"><button class="rounded bg-indigo-600 px-4 py-2 text-white">Search</button></form>
@if($search)<section><h2 class="text-xl font-bold">{{ $search['scanned'] }} scanned · {{ $search['with_metafield'] }} with metafield · {{ count($search['orders']) }} matches</h2>@if($search['truncated'])<p class="text-amber-700">Results truncated after {{ $search['pages'] }} pages.</p>@endif<ul>@foreach($search['orders'] as $order)<li><a class="text-indigo-600" href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $order['id'] }}">{{ $order['name'] }}</a> · {{ $order['metafield']['value'] }}</li>@endforeach</ul></section>@endif
<form class="grid gap-3 rounded-xl border bg-white p-5 dark:bg-slate-900" method="POST" action="{{ route('metafields.lookup') }}">@csrf<h2 class="text-xl font-bold">Inspect orders</h2><textarea class="rounded border px-3 py-2" name="orders" placeholder="1001, 1002">{{ old('orders') }}</textarea>@error('orders')<p class="text-red-600">{{ $message }}</p>@enderror<input class="rounded border px-3 py-2" name="filter" placeholder="Optional namespace, key, or value filter" value="{{ old('filter') }}"><button class="rounded bg-indigo-600 px-4 py-2 text-white">Look up</button></form>
@if($lookup)<section class="space-y-3">@foreach($lookup as $row)<div class="rounded-xl border bg-white p-4 dark:bg-slate-900"><h3 class="font-bold">{{ $row['name'] ?? '#'.$row['number'] }} {{ $row['found'] ? '' : '— not found' }}</h3>@foreach($row['metafields'] as $metafield)<p>{{ $metafield['namespace'] }}.{{ $metafield['key'] }} = {{ $metafield['value'] }}</p>@endforeach</div>@endforeach</section>@endif</div>
@endsection
