@extends('layouts.app')

@section('content')
<div class="flex flex-col gap-6">
<section><p class="text-sm font-medium text-indigo-600 dark:text-indigo-400">Fulfillment report</p><h1 class="mt-1 text-3xl font-bold">Address Scanner</h1><p class="mt-2 text-slate-500 dark:text-slate-400">Find incomplete, invalid, short, or carrier-incompatible shipping addresses on paid orders.</p></section>
<form class="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-3 dark:border-slate-800 dark:bg-slate-900" method="POST" action="{{ route('reports.address-check.store') }}">@csrf
@foreach (['start_date' => ['From', $startDate], 'end_date' => ['To', $endDate]] as $field => [$label, $value])<div><label class="text-sm font-medium" for="{{ $field }}">{{ $label }}</label><input class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-950" id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field, $value) }}">@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div>@endforeach
<div class="flex flex-col justify-end gap-2"><label><input name="unfulfilled_only" type="checkbox" value="1" @checked(old('unfulfilled_only', $unfulfilledOnly))> Unfulfilled only</label><label><input name="po_box_only" type="checkbox" value="1" @checked(old('po_box_only', $poBoxOnly))> PO Box issues only</label><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white" type="submit">Run report</button></div></form>
@if($configurationError)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Shopify credentials are incomplete for the active store.</div>@endif
@if($reportFailed)<div class="rounded-xl bg-red-50 p-4 text-red-800">The report could not be completed. Check Shopify and try again.</div>@endif
@if($result)<section class="flex flex-col gap-4"><h2 class="text-2xl font-bold">{{ $result->scanned }} scanned · {{ $result->critical }} critical · {{ $result->warnings }} warnings</h2>@if($result->truncated)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Results are incomplete: orders truncated after {{ $result->pages }} pages.</div>@endif
<div class="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><table class="min-w-full text-left text-sm"><thead><tr><th class="px-4 py-3">Severity</th><th class="px-4 py-3">Order</th><th class="px-4 py-3">Email</th><th class="px-4 py-3">Address</th><th class="px-4 py-3">Issues</th></tr></thead><tbody>
@forelse($result->rows as $row)<tr class="align-top"><td class="px-4 py-3 font-semibold">{{ ucfirst($row['severity']) }}</td><td class="px-4 py-3">@if($row['id'])<a class="text-indigo-600" href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $row['id'] }}" target="_blank" rel="noopener noreferrer">{{ $row['number'] }}</a>@else{{ $row['number'] }}@endif<br>{{ $row['created_at'] }}</td><td class="px-4 py-3">{{ $row['email'] }}</td><td class="px-4 py-3">{{ $row['address']['address1'] ?? 'Missing' }}<br>{{ $row['address']['city'] ?? '' }} {{ $row['address']['zip'] ?? '' }} {{ $row['address']['country_code'] ?? '' }}</td><td class="px-4 py-3"><ul class="list-disc pl-5">@foreach($row['issues'] as $issue)<li>{{ $issue['message'] }}</li>@endforeach</ul></td></tr>@empty<tr><td class="px-4 py-8 text-center text-slate-500" colspan="5">No address issues were found.</td></tr>@endforelse
</tbody></table></div></section>@endif
</div>
@endsection
