@extends('layouts.app')
@section('content')
<div class="flex flex-col gap-6"><section><p class="text-sm font-medium text-indigo-600">Fulfillment report</p><h1 class="text-3xl font-bold">Shipment Aging</h1><p class="text-slate-500">Live ShipStation awaiting-shipment orders older than the threshold.</p></section>
<form class="flex flex-wrap items-end gap-4 rounded-xl border p-5" method="POST" action="{{ route('reports.shipment-aging.store') }}">@csrf<div><label for="threshold">Older than days</label><input class="block rounded-lg border px-3 py-2" id="threshold" name="threshold" type="number" min="1" max="365" value="{{ old('threshold',$threshold) }}">@error('threshold')<p class="text-red-600">{{ $message }}</p>@enderror</div><button class="rounded-lg bg-indigo-600 px-5 py-2 text-white">Run report</button></form>
@error('export')<div class="rounded-xl bg-red-50 p-4">{{ $message }}</div>@enderror @if($configurationError)<div class="rounded-xl bg-amber-50 p-4">ShipStation credentials are incomplete for the active store.</div>@endif @if($reportFailed)<div class="rounded-xl bg-red-50 p-4">The report could not be completed. Check ShipStation and try again.</div>@endif
@if($result)<div class="flex justify-between gap-3"><h2 class="text-2xl font-bold">{{ $result->scanned }} awaiting orders scanned · {{ count($result->rows) }} older than {{ $result->threshold }} days</h2><form method="POST" action="{{ route('reports.shipment-aging.export') }}">@csrf<input type="hidden" name="threshold" value="{{ $result->threshold }}"><button class="rounded-lg border px-4 py-2">Download CSV</button></form></div>
<div class="grid gap-4 md:grid-cols-2"><div class="rounded-xl border p-4"><h3 class="font-bold">By SKU</h3>@foreach(array_slice($result->bySku,0,8) as $row)<p>{{ $row['sku'] }} · {{ $row['orders'] }} orders · {{ $row['qty'] }} qty · oldest {{ $row['oldest_days'] }}d</p>@endforeach</div><div class="rounded-xl border p-4"><h3 class="font-bold">By type</h3>@foreach(array_slice($result->byType,0,8) as $row)<p>{{ $row['type'] }} · {{ $row['orders'] }} orders · oldest {{ $row['oldest_days'] }}d</p>@endforeach</div></div>
<div class="overflow-x-auto rounded-xl border"><table class="min-w-full text-left"><thead><tr><th class="p-3">Order</th><th>Date</th><th>Days</th><th>Customer</th><th>Total</th><th>Type</th><th>SKUs</th></tr></thead><tbody>@forelse($result->rows as $row)<tr><td class="p-3 font-semibold">{{ $row['order_number'] }}</td><td>{{ $row['order_date'] }}</td><td>{{ $row['days'] }}d</td><td>{{ $row['customer'] }}<br>{{ $row['email'] }}</td><td>{{ number_format($row['total'],2) }}</td><td>{{ $row['order_type'] }}</td><td>@foreach($row['skus'] as $sku=>$qty)<div>{{ $sku }} ×{{ $qty }}</div>@endforeach</td></tr>@empty<tr><td class="p-6 text-center" colspan="7">No aging shipments.</td></tr>@endforelse</tbody></table></div>@endif</div>
@endsection
