@extends('layouts.app')
@section('content')
<div class="flex flex-col gap-6"><section><p class="text-sm font-medium text-indigo-600">Compliance report</p><h1 class="text-3xl font-bold">Tax Audit</h1><p class="text-slate-500">Review paid, non-exempt orders above the minimum where Shopify charged no tax.</p></section>
<form class="grid gap-4 rounded-xl bg-white p-5 sm:grid-cols-4 dark:bg-slate-900" method="POST" action="{{ route('reports.tax-audit.store') }}">@csrf
@foreach(['start_date'=>['From',$startDate],'end_date'=>['To',$endDate]] as $field=>[$label,$value])<div><label for="{{ $field }}">{{ $label }}</label><input class="w-full rounded border p-2 dark:bg-slate-950" id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field,$value) }}">@error($field)<p class="text-red-600">{{ $message }}</p>@enderror</div>@endforeach
<div><label for="minimum">Minimum total</label><input class="w-full rounded border p-2 dark:bg-slate-950" id="minimum" name="minimum" type="number" min="0" step="1" value="{{ old('minimum',$minimum) }}">@error('minimum')<p class="text-red-600">{{ $message }}</p>@enderror</div><div class="flex items-end"><button class="rounded bg-indigo-600 px-5 py-2.5 text-white">Run report</button></div></form>
@if($reportFailed)<div class="rounded bg-red-50 p-4 text-red-800">The report could not be completed. Check Shopify and try again.</div>@endif
@if($configurationError)<div class="rounded bg-amber-50 p-4 text-amber-800">Shopify credentials are incomplete for the active store.</div>@endif
@if($result)<section><h2 class="text-2xl font-bold">{{ $result->scanned }} scanned · {{ count($result->rows) }} zero-tax orders</h2>@if($result->truncated)<p class="text-amber-700">Results truncated after {{ $result->pages }} pages.</p>@endif<div class="overflow-x-auto"><table class="min-w-full text-left"><thead><tr><th>Order</th><th>Date</th><th>Email</th><th>Total</th></tr></thead><tbody>@forelse($result->rows as $row)<tr><td>@if($row['id'])<a href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $row['id'] }}">{{ $row['number'] }}</a>@else{{ $row['number'] }}@endif</td><td>{{ $row['created_at'] }}</td><td>{{ $row['email'] }}</td><td>{{ number_format($row['total'],2) }} {{ $row['currency'] }}</td></tr>@empty<tr><td colspan="4">No qualifying zero-tax orders found.</td></tr>@endforelse</tbody></table></div></section>@endif</div>
@endsection
