@extends('layouts.app')

@section('content')
<div class="flex flex-col gap-6">
<section><h1 class="text-3xl font-bold">Customer Lookup</h1><p class="mt-2 text-slate-500 dark:text-slate-400">Full Shopify order history and spend summary by email.</p></section>
<form class="flex gap-3 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900" method="POST" action="{{ route('customers.lookup.store') }}">@csrf<div class="grow"><label class="text-sm font-medium" for="email">Email</label><input class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-950" id="email" name="email" type="email" value="{{ old('email', $email) }}" autofocus>@error('email')<p class="text-sm text-red-600">{{ $message }}</p>@enderror</div><div class="flex items-end"><button class="rounded-lg bg-indigo-600 px-5 py-2.5 font-semibold text-white" type="submit">Look up</button></div></form>
@if($configurationError)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Shopify credentials are incomplete for the active store.</div>@endif
@if($lookupFailed)<div class="rounded-xl bg-red-50 p-4 text-red-800">The lookup could not be completed. Check Shopify and try again.</div>@endif
@if($result)<section class="flex flex-col gap-4"><div class="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 class="text-2xl font-bold">{{ trim(($result->customer['firstName'] ?? '').' '.($result->customer['lastName'] ?? '')) ?: $result->email }}</h2><p>{{ $result->email }}</p><p class="mt-3">{{ count($result->orders) }}{{ $result->truncated ? '+' : '' }} orders · {{ $result->currency }} {{ number_format($result->totalSpent, 2) }} spent · {{ $result->paid }} paid · {{ $result->cancelled }} cancelled</p>@if($result->tags)<div class="mt-3 flex flex-wrap gap-2">@foreach(array_slice($result->tags, 0, 30, true) as $tag => $count)<span class="rounded bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">{{ $tag }} · {{ $count }}</span>@endforeach</div>@endif</div>
@if($result->truncated)<div class="rounded-xl bg-amber-50 p-4 text-amber-800">Results are incomplete: orders truncated after {{ $result->pages }} pages.</div>@endif
<div class="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><table class="min-w-full text-left text-sm"><thead><tr><th class="px-4 py-3">Order</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">Financial</th><th class="px-4 py-3">Fulfillment</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Tags</th></tr></thead><tbody>@forelse($result->orders as $order)<tr class="{{ $order['cancelled_at'] ? 'opacity-50' : '' }}"><td class="px-4 py-3">@if($order['id'])<a class="text-indigo-600" href="https://{{ $activeStore->shopify_store }}.myshopify.com/admin/orders/{{ $order['id'] }}" target="_blank" rel="noopener noreferrer">{{ $order['name'] }}</a>@else{{ $order['name'] }}@endif</td><td class="px-4 py-3">{{ substr((string) $order['created_at'], 0, 10) }}</td><td class="px-4 py-3">{{ $order['financial_status'] ?: '-' }}</td><td class="px-4 py-3">{{ $order['fulfillment_status'] ?: '-' }}</td><td class="px-4 py-3">{{ $order['currency'] ?? '' }} {{ number_format((float) $order['total_price'], 2) }}</td><td class="px-4 py-3">{{ implode(', ', $order['tags'] ?? []) }}</td></tr>@empty<tr><td class="px-4 py-8 text-center text-slate-500" colspan="6">No orders found for {{ $result->email }}.</td></tr>@endforelse</tbody></table></div></section>@endif
</div>
@endsection
